In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_loan = pd.read_csv('../data/loan_data.csv')

In [5]:
df_loan_vf = df_loan.copy()

In [37]:
df_loan_vf = df_loan_vf.rename(columns={
    'Gender': 'Genre',
    'Married': 'Marier',
    'Dependents': 'Personnes_a_charge',
    'Education': 'Niveau_etude',
    'Self_Employed': 'Independant',
    'ApplicantIncome': 'Revenu_demandeur',
    'CoapplicantIncome': 'Revenu_co_demandeur',
    'LoanAmount': 'Montant_pret',
    'Loan_Amount_Term': 'Duree_pret',
    'Credit_History': 'Historique_credit',
    'Property_Area': 'Zone_habitation',
    'Loan_Status': 'Statut_pret'
})

In [38]:
df_loan_vf

,Loan_ID,Genre,Marie,Personnes_a_charge,Niveau_etude,Independant,Revenu_demandeur,Revenu_co_demandeur,Montant_pret,Duree_pret,Historique_credit,Zone_habitation,Statut_pret
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777.0,113.0,360.0,1.0,Urban,NaN
977,LP002975,Male,Yes,0,Graduate,No,4158,709.0,115.0,360.0,1.0,Urban,NaN
978,LP002980,Male,No,0,Graduate,No,3250,1993.0,126.0,360.0,NaN,Semiurban,NaN
979,LP002986,Male,Yes,0,Graduate,No,5000,2393.0,158.0,360.0,1.0,Rural,NaN
980,LP002989,Male,No,0,Graduate,Yes,9200,0.0,98.0,180.0,1.0,Rural,NaN

In [39]:
df_loan_vf["Statut_pret"].value_counts()

Statut_pret
Y    422
N    192
Name: count, dtype: int64

In [40]:
df_loan_vf["Statut_pret"].isna().sum()
# On a 367 valeurs manquantes dans cette colonnes, ce qui représente 1/3 du dataset
# et peut fausser notre modèle de machin learning on doit impérativement
# trouver un moyen de combler ces valeurs 

# Décision : Ignorez les lignes sans statut pret et se concentrer sur celles qui en ont.

np.int64(367)

In [41]:
#Split du dataset en deux df. Mise de coté des lignes sans réponse au pret. 
df_avec_cible = df_loan_vf[df_loan_vf['Statut_pret'].notna()].copy()
df_sans_cible = df_loan_vf[df_loan_vf['Statut_pret'].isna()].copy()

In [42]:
df_avec_cible.shape

(614, 13)

In [43]:
df_avec_cible.describe()

,Revenu_demandeur,Revenu_co_demandeur,Montant_pret,Duree_pret,Historique_credit
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [44]:
df_avec_cible.info()

<class 'pandas.core.frame.DataFrame'>
Index: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Loan_ID              614 non-null    object
 1   Genre                601 non-null    object
 2   Marie                611 non-null    object
 3   Personnes_a_charge   599 non-null    object
 4   Niveau_etude         614 non-null    object
 5   Independant          582 non-null    object
 6   Revenu_demandeur     614 non-null    int64
 7   Revenu_co_demandeur  614 non-null    float64
 8   Montant_pret         592 non-null    float64
 9   Duree_pret           600 non-null    float64
 10  Historique_credit    564 non-null    float64
 11  Zone_habitation      614 non-null    object
 12  Statut_pret          614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 67.2+ KB

In [45]:
df_avec_cible.isna().sum()

Loan_ID                 0
Genre                  13
Marie                   3
Personnes_a_charge     15
Niveau_etude            0
Independant            32
Revenu_demandeur        0
Revenu_co_demandeur     0
Montant_pret           22
Duree_pret             14
Historique_credit      50
Zone_habitation         0
Statut_pret             0
dtype: int64

## Nettoyage

- Données manquante
- Valeurs abérrante

In [46]:
df_avec_cible.groupby("Zone_habitation")["Statut_pret"].value_counts()

Zone_habitation  Statut_pret
Rural            Y              110
                 N               69
Semiurban        Y              179
                 N               54
Urban            Y              133
                 N               69
Name: count, dtype: int64

In [47]:
graduate = df_avec_cible[df_avec_cible['Niveau_etude'] == 'Not Graduate']
print(graduate.shape)

(134, 13)

In [48]:
print(len(graduate))

134